services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - /app/node_modules # Prevents overwriting node_modules inside container
    command: ['bun', 'start']
