services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - BUN_ENV="production"
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - COMPOSE_BAKE=true
    volumes:
      - /app/node_modules # Prevents overwriting node_modules inside container
    command: ['bun', 'start']
